export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
  "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
  "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Côte d'Ivoire", "Cabo Verde",
  "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo",
  "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
  "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland",
  "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
  "Guinea-Bissau", "Guyana", "Haiti", "Holy See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran",
  "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati",
  "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania",
  "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius",
  "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia",
  "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway",
  "Oman", "Pakistan", "Palau", "Palestine State", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland",
  "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
  "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
  "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland",
  "Syria", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey",
  "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu",
  "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];

export const CURRENCIES = [
  { value: "USD", label: "US Dollar — USD ($)" },
  { value: "EUR", label: "Euro — EUR (€)" },
  { value: "GBP", label: "British Pound — GBP (£)" },
  { value: "ETB", label: "Ethiopian Birr — ETB (Br)" },
  { value: "JPY", label: "Japanese Yen — JPY (¥)" },
  { value: "AUD", label: "Australian Dollar — AUD ($)" },
  { value: "CAD", label: "Canadian Dollar — CAD ($)" },
  { value: "CHF", label: "Swiss Franc — CHF (CHF)" },
  { value: "CNY", label: "Chinese Yuan — CNY (¥)" },
  { value: "HKD", label: "Hong Kong Dollar — HKD ($)" },
  { value: "NZD", label: "New Zealand Dollar — NZD ($)" },
  { value: "SEK", label: "Swedish Krona — SEK (kr)" },
  { value: "KRW", label: "South Korean Won — KRW (₩)" },
  { value: "SGD", label: "Singapore Dollar — SGD ($)" },
  { value: "NOK", label: "Norwegian Krone — NOK (kr)" },
  { value: "MXN", label: "Mexican Peso — MXN ($)" },
  { value: "INR", label: "Indian Rupee — INR (₹)" },
  { value: "RUB", label: "Russian Ruble — RUB (₽)" },
  { value: "ZAR", label: "South African Rand — ZAR (R)" },
  { value: "BRL", label: "Brazilian Real — BRL (R$)" },
  { value: "TRY", label: "Turkish Lira — TRY (₺)" },
  { value: "TWD", label: "New Taiwan Dollar — TWD (NT$)" },
  { value: "DKK", label: "Danish Krone — DKK (kr)" },
  { value: "PLN", label: "Polish Zloty — PLN (zł)" },
  { value: "THB", label: "Thai Baht — THB (฿)" },
  { value: "IDR", label: "Indonesian Rupiah — IDR (Rp)" },
  { value: "HUF", label: "Hungarian Forint — HUF (Ft)" },
  { value: "CZK", label: "Czech Koruna — CZK (Kč)" },
  { value: "ILS", label: "Israeli New Shekel — ILS (₪)" },
  { value: "CLP", label: "Chilean Peso — CLP ($)" },
  { value: "PHP", label: "Philippine Peso — PHP (₱)" },
  { value: "AED", label: "UAE Dirham — AED (د.إ)" },
  { value: "COP", label: "Colombian Peso — COP ($)" },
  { value: "SAR", label: "Saudi Riyal — SAR (ر.س)" },
  { value: "MYR", label: "Malaysian Ringgit — MYR (RM)" },
  { value: "RON", label: "Romanian Leu — RON (lei)" },
  { value: "KES", label: "Kenyan Shilling — KES (KSh)" },
  { value: "NGN", label: "Nigerian Naira — NGN (₦)" },
  { value: "GHS", label: "Ghanaian Cedi — GHS (GH₵)" },
  { value: "UGX", label: "Ugandan Shilling — UGX (USh)" },
  { value: "TZS", label: "Tanzanian Shilling — TZS (TSh)" },
  { value: "RWF", label: "Rwandan Franc — RWF (FRw)" }
];

export const TIMEZONES = [
  { value: "Africa/Addis_Ababa", label: "Africa/Addis_Ababa — Ethiopia" },
  { value: "Africa/Nairobi", label: "Africa/Nairobi — Kenya" },
  { value: "Africa/Cairo", label: "Africa/Cairo — Egypt" },
  { value: "Africa/Johannesburg", label: "Africa/Johannesburg — South Africa" },
  { value: "Africa/Lagos", label: "Africa/Lagos — Nigeria" },
  { value: "Africa/Accra", label: "Africa/Accra — Ghana" },
  { value: "Europe/London", label: "Europe/London — United Kingdom" },
  { value: "Europe/Berlin", label: "Europe/Berlin — Germany" },
  { value: "Europe/Paris", label: "Europe/Paris — France" },
  { value: "Europe/Rome", label: "Europe/Rome — Italy" },
  { value: "Europe/Madrid", label: "Europe/Madrid — Spain" },
  { value: "Europe/Moscow", label: "Europe/Moscow — Russia" },
  { value: "Europe/Istanbul", label: "Europe/Istanbul — Turkey" },
  { value: "America/New_York", label: "America/New_York — United States (Eastern)" },
  { value: "America/Chicago", label: "America/Chicago — United States (Central)" },
  { value: "America/Denver", label: "America/Denver — United States (Mountain)" },
  { value: "America/Los_Angeles", label: "America/Los_Angeles — United States (Pacific)" },
  { value: "America/Toronto", label: "America/Toronto — Canada" },
  { value: "America/Mexico_City", label: "America/Mexico_City — Mexico" },
  { value: "America/Sao_Paulo", label: "America/Sao_Paulo — Brazil" },
  { value: "America/Buenos_Aires", label: "America/Buenos_Aires — Argentina" },
  { value: "Asia/Dubai", label: "Asia/Dubai — United Arab Emirates" },
  { value: "Asia/Tokyo", label: "Asia/Tokyo — Japan" },
  { value: "Asia/Shanghai", label: "Asia/Shanghai — China" },
  { value: "Asia/Singapore", label: "Asia/Singapore — Singapore" },
  { value: "Asia/Hong_Kong", label: "Asia/Hong_Kong — Hong Kong" },
  { value: "Asia/Seoul", label: "Asia/Seoul — South Korea" },
  { value: "Asia/Kolkata", label: "Asia/Kolkata — India" },
  { value: "Asia/Bangkok", label: "Asia/Bangkok — Thailand" },
  { value: "Asia/Jakarta", label: "Asia/Jakarta — Indonesia" },
  { value: "Asia/Riyadh", label: "Asia/Riyadh — Saudi Arabia" },
  { value: "Australia/Sydney", label: "Australia/Sydney — Australia (Eastern)" },
  { value: "Australia/Melbourne", label: "Australia/Melbourne — Australia" },
  { value: "Australia/Perth", label: "Australia/Perth — Australia (Western)" },
  { value: "Pacific/Auckland", label: "Pacific/Auckland — New Zealand" },
  { value: "Pacific/Fiji", label: "Pacific/Fiji — Fiji" },
  { value: "Pacific/Honolulu", label: "Pacific/Honolulu — Hawaii" }
];

export const PHONE_COUNTRIES = [
  { code: 'US', dialCode: '+1', flag: '🇺🇸', name: 'United States' },
  { code: 'GB', dialCode: '+44', flag: '🇬🇧', name: 'United Kingdom' },
  { code: 'ET', dialCode: '+251', flag: '🇪🇹', name: 'Ethiopia' },
  { code: 'CA', dialCode: '+1', flag: '🇨🇦', name: 'Canada' },
  { code: 'AU', dialCode: '+61', flag: '🇦🇺', name: 'Australia' },
  { code: 'DE', dialCode: '+49', flag: '🇩🇪', name: 'Germany' },
  { code: 'FR', dialCode: '+33', flag: '🇫🇷', name: 'France' },
  { code: 'IT', dialCode: '+39', flag: '🇮🇹', name: 'Italy' },
  { code: 'ES', dialCode: '+34', flag: '🇪🇸', name: 'Spain' },
  { code: 'IN', dialCode: '+91', flag: '🇮🇳', name: 'India' },
  { code: 'JP', dialCode: '+81', flag: '🇯🇵', name: 'Japan' },
  { code: 'CN', dialCode: '+86', flag: '🇨🇳', name: 'China' },
  { code: 'BR', dialCode: '+55', flag: '🇧🇷', name: 'Brazil' },
  { code: 'ZA', dialCode: '+27', flag: '🇿🇦', name: 'South Africa' },
  { code: 'NG', dialCode: '+234', flag: '🇳🇬', name: 'Nigeria' },
  { code: 'KE', dialCode: '+254', flag: '🇰🇪', name: 'Kenya' },
  { code: 'AE', dialCode: '+971', flag: '🇦🇪', name: 'United Arab Emirates' },
  { code: 'SA', dialCode: '+966', flag: '🇸🇦', name: 'Saudi Arabia' },
  { code: 'MX', dialCode: '+52', flag: '🇲🇽', name: 'Mexico' },
  { code: 'AR', dialCode: '+54', flag: '🇦🇷', name: 'Argentina' },
  { code: 'RU', dialCode: '+7', flag: '🇷🇺', name: 'Russia' },
  { code: 'KR', dialCode: '+82', flag: '🇰🇷', name: 'South Korea' },
  { code: 'TR', dialCode: '+90', flag: '🇹🇷', name: 'Turkey' },
  { code: 'EG', dialCode: '+20', flag: '🇪🇬', name: 'Egypt' },
  { code: 'GH', dialCode: '+233', flag: '🇬🇭', name: 'Ghana' }
];
